### ISSUE TITLE
imageview: opening the filter options dialog fails with TypeError

### ISSUE THREAD

**Issue by RKrahl** [RKrahl/photo-tools#44]
If images are selected by explicit file names in `imageview`, opening the filter options dialog fails with `TypeError`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/photo/qt/imageViewer.py", line 394, in filterOptions
    self.filterDialog.setfilter(self.imgFilter)
  File "/usr/lib/python3.6/site-packages/photo/qt/filterDialog.py", line 203, in setfilter
    self.filelistFilterOption.setOption(imgFilter.filelist)
  File "/usr/lib/python3.6/site-packages/photo/qt/filterDialog.py", line 172, in setOption
    self.entry.setText(" ".join(sorted(filelist)))
TypeError: sequence item 0: expected str instance, PosixPath found
```

**Comment by RKrahl** [comment]
The cause of this bug is clear: the `filelist` attribute of `class IdxFilter` has been changed to a set of `Path` objects.  But in `FilterDialog.setfilter()` the value of `filelistFilterOption` is initialized by joining the `filelist` elements to a string.  This is a regression created in cab8e2d.
