### ISSUE TITLE
imageview crashes with ZeroDivisionError if no tags are set in the index

### ISSUE THREAD

**Issue by RKrahl** [RKrahl/photo-tools#6]
Start with an image index having no tags for any image.  E.g. start with a new index:
```
$ photoidx create
$ photoidx lstags
$ imageview 
Traceback (most recent call last):
  File "/usr/bin/imageview", line 20, in <module>
    imageViewer = ImageViewer(idx, idxfilter, args.scale)
  File "/usr/lib/python2.7/site-packages/photo/qt/imageViewer.py", line 25, in __init__
    self.tagSelectDialog = TagSelectDialog(taglist)
  File "/usr/lib/python2.7/site-packages/photo/qt/tagSelectDialog.py", line 18, in __init__
    nrow = int(math.ceil(len(self.taglist)/ncol))
ZeroDivisionError: division by zero
```

**Comment by RKrahl** [comment]
Blocks #11.
